document.addEventListener('DOMContentLoaded', () => {
    // --- Scroll Spy Logic ---
    const sections = document.querySelectorAll('section');
    const navLi = document.querySelectorAll('.sticky-nav ul li a');

    function updateActiveLink() {
        let current = '';

        sections.forEach(section => {
            const sectionTop = section.offsetTop;
            const sectionHeight = section.clientHeight;
            // Adjustment for sticky header height (approx 60px) + some buffer
            if (scrollY >= (sectionTop - 150)) {
                current = section.getAttribute('id');
            }
        });

        navLi.forEach(a => {
            a.classList.remove('active');
            if (a.getAttribute('href').includes(current)) {
                a.classList.add('active');
            }
        });
    }

    window.addEventListener('scroll', updateActiveLink);
    updateActiveLink(); // Initial check

    // --- Multi-language Support ---
    const langButtons = document.querySelectorAll('.lang-btn');
    const translatableElements = document.querySelectorAll('[data-i18n]');
    const currentLang = localStorage.getItem('language') || 'pt';

    // Translation Dictionary
    const translations = {
        pt: {
            nav_entradas: "Entradas",
            nav_drinks: "Drinks",
            nav_saladas: "Saladas",
            nav_mariscos: "Peixe & Camarão",
            nav_carnes: "Carnes",
            nav_kids: "Kids",
            nav_caldos: "Caldos",
            nav_burgers: "Burgers",
            nav_porcoes: "Porções",
            nav_sobremesas: "Sobremesas",
            nav_bebidas: "Bebidas",
            nav_peixes: "Risoto & Massa",
            sponsors_label: "Oferecimento",
            select_language: "Selecione o idioma",

            section_entradas_title: "Para Começar",
            section_entradas_subtitle: "",
            item_bolinho_peixe_title: "Bolinho de Peixe",
            item_bolinho_peixe_desc: "12 Unidades",
            item_camarao_empanado_title: "Camarão Empanado",
            item_camarao_empanado_desc: "12 Unidades",
            item_camarao_alho_oleo_title: "Camarão ao Alho e Óleo",
            item_camarao_alho_oleo_desc: "",
            item_batata_frita_title: "Batata Frita",
            item_batata_frita_desc: "Molho rosé.",
            item_macaxeira_frita_title: "Macaxeira Frita",
            item_macaxeira_frita_desc: "",
            item_file_aperitivo_title: "Filé em tiras com Farofa de Banana",
            item_file_aperitivo_desc: "Filé em tiras, acebolado e com farofa de banana.",
            item_calabresa_acebolada_title: "Calabresa Acebolada",
            item_calabresa_acebolada_desc: "Acompanha farofa e torrada",
            item_macaxeira_bacon_title: "Macaxeira frita com bacon",
            item_macaxeira_bacon_desc: "Molho rosé.",
            item_caranguejo_refogado_title: "Caranguejo Refogado",
            item_caranguejo_refogado_desc: "Farofa.",
            item_camarao_crocante_title: "Camarão Crocante",
            item_camarao_crocante_desc: "Camarão empanado na farinha especial e molho rosé.",
            item_panceta_porco_title: "Panceta de Porco",
            item_panceta_porco_desc: "Corte suíno especial assado, pêra portuguesa gratinada e mostarda com mel.",
            item_ostra_fonduta_title: "Ostra com Fonduta de Queijo",
            item_ostra_fonduta_desc: "Gratinada ao creme de parmesão, torradas - 6 und.",
            item_carpaccio_pesto_title: "Carpaccio ao Pesto",
            item_carpaccio_pesto_desc: "Lâminas finas de carne, molho pesto, parmesão e torradas.",
            item_isca_peixe_title: "Isca de Peixe Crocante",
            item_isca_peixe_desc: "Farofa e molho rosé.",
            item_linguica_jambu_title: "Linguiça Artesanal com recheio de Jambú",
            item_linguica_jambu_desc: "Grelhada, acompanha molho de pimenta com tucupi, farofa e vinagrete.",
            item_tabua_frios_title: "Tábua de Frios",
            item_tabua_frios_desc: "Queijos, salame, azeitona, uva, creme de queijo e torradas.",

            section_drinks_title: "Drinks",
            section_drinks_subtitle_autorais: "Autorais",
            tag_new: "(Novo)",

            item_o_barquinho_title: "O Barquinho",
            item_o_barquinho_desc: "Rum, Aperol, abacaxi, xarope de açúcar e limão.",
            item_macarico_title: "Maçarico",
            item_macarico_desc: "Gin de jambu, limão siciliano, xarope de açúcar e angustura.",

            item_olho_grego_title: "Olho Grego",
            item_olho_grego_desc: "Gin, curaçau blue, limão siciliano e espuma gengibre.",
            item_la_passion_title: "La Passion",
            item_la_passion_desc: "Vodka, morango, pitaya vermelha, açúcar e gelo.",

            section_drinks_subtitle_atuais: "Atuais",
            item_moscow_mule_title: "Moscow Mule",
            item_moscow_mule_desc: "Vodka, limão siciliano, xarope de gengibre e espuma de gengibre.",
            item_gin_mule_title: "Gin Mule",
            item_gin_mule_desc: "Gin, limão siciliano, xarope de gengibre e espuma de gengibre.",
            item_gin_tonica_title: "Gin Tônica",
            item_gin_tonica_desc: "Gin, água tônica e harmonização com especiarias.",
            item_spritz_aperol_title: "Spritz Aperol",
            item_spritz_aperol_desc: "Espumante, aperol e soda.",
            item_mimosa_title: "Mimosa",
            item_mimosa_desc: "Espumante e suco de laranja.",

            section_drinks_subtitle_antologicos: "Antológicos",
            item_negroni_title: "Negroni",
            item_negroni_desc: "Gin, vermute, campari e twist de laranja.",
            item_mojito_title: "Mojito",
            item_mojito_desc: "Rum, limão e hortelã.",
            item_marguerita_title: "Marguerita",
            item_marguerita_desc: "Tequila, cointreau, curaçau blue e limão taiti.",

            item_caipirosca_title: "Caipirosca",
            item_caipirosca_desc: "Vodka importada, frutas da estação, açúcar e gelo.",
            item_caipirinha_title: "Caipirinha",
            item_caipirinha_desc: "Cachaça, limão taiti, açúcar e gelo.",
            item_coquetel_frutas_title: "Coquetel de Frutas",
            item_coquetel_frutas_desc: "Mix de frutas, vodka, leite condensado, creme de leite e groselha e chantilly.",

            section_drinks_subtitle_sem_alcool: "Sem Álcool",
            item_coquetel_frutas_sem_alcool_title: "Coquetel de Frutas",
            item_coquetel_frutas_sem_alcool_desc: "Mix de frutas, leite condensado, creme de leite, groselha e chantilly.",

            section_saladas_title: "Saladas",
            item_salada_caesar_title: "Salada Caesar",
            item_salada_caesar_desc: "Mix de folhas, tiras de frango grelhado, croutons e parmesão ao molho caesar.",
            item_salada_feijao_manteiguinha_title: "Salada com Feijão manteiguinha",
            item_salada_feijao_manteiguinha_desc: "Mix de Folhas, vinagrete de feijão manteiguinha, tomate, cenoura, abobrinha e queijo.",

            section_mariscos_title: "Peixe & Camarão",
            item_pescada_tucupi_title: "Pescada Grelhada a la creme de tucupi",
            item_pescada_tucupi_desc: "Arroz com tucupi e jambú e Pirão com camarão",
            item_pescada_camarao_title: "Pescada Grelhada ao molho de Camarão",
            item_pescada_camarao_desc: "Arroz branco e purê de batata",
            item_camarao_solar_title: "Camarão Crocante Solar",
            item_camarao_solar_desc: "Empanado e gratinado com queijo, arroz à piamontese e fritos",
            item_caldeirada_pescada_title: "Caldeirada de Pescada Amarela",
            item_caldeirada_pescada_desc: "Pescada, camarão, ovo cozido, legumes, arroz branco e pirão",
            item_peixe_frito_regional_title: "Peixe Frito Regional",
            item_peixe_frito_regional_desc: "Arroz branco, farofa e vinagrete com feijão manteiguinha",
            item_pescada_solar_title: "Pescada ao Solar",
            item_pescada_solar_desc: "Empanado na farinha especial, arroz cremoso e purê de batata.",

            section_peixes_title: "Risoto & Massa",
            item_peixe_amazonico_title: "Peixe Amazônico na crosta de alho",
            item_peixe_amazonico_desc: "Filhote, risoto de parmesão e molho de azeitona preta",
            item_espaguete_bolonhesa_title: "Espaguete ao molho a bolonhesa",
            item_espaguete_bolonhesa_desc: "Individual",

            section_carnes_title: "Carnes",
            item_file_alfredo_title: "Filé Alfredo",
            item_file_alfredo_desc: "Filé grelhado e fettuccine ao creme de parmesão ao aroma de bacon",
            item_file_solar_title: "Filé Solar",
            item_file_solar_desc: "Grelhado ao molho de cebola, arroz piamontese, batata frita e farofa de ovo",
            item_file_grelhado_solar_title: "Filé Grelhado Solar",
            item_file_grelhado_solar_desc: "Grelhado, arroz , farofa e fritas",

            section_kids_title: "Kids",
            item_file_cubinhos_title: "Filé em Cubinhos",
            item_file_cubinhos_desc: "Grelhado em cubo, arroz branco, farofa de ovo e fritas",
            item_isca_milanesa_title: "Isca à milanesa",
            item_isca_milanesa_desc: "Pescada, arroz branco, farofa e purê de batata",

            section_caldos_title: "Caldos e Sopas",
            section_caldos_subtitle: "(porção individual, acompanha torradas)",
            item_sopa_caranguejo_title: "Sopa de Caranguejo",
            item_canja_title: "Canja",
            item_caldo_legumes_title: "Caldo de Legumes",
            item_caldo_tucupi_title: "Caldo de Tucupi",
            item_caldo_tucupi_desc: "Jambú e camarão",

            section_burgers_title: "Burgers",
            section_burgers_subtitle: "Acompanha salada de mix de folhas, tomate, cenoura ralada e cebola roxa",
            item_file_do_reino_title: "Filé do Reino",
            item_file_do_reino_desc: "Pão Baguete, filé, queijo do reino e fritas",
            item_burger_solar_title: "Burger Solar",
            item_burger_solar_desc: "Pão, blend artesanal, queijo, calabresa, ovo e batata rústica",
            item_burger_kids_title: "Burger kids",
            item_burger_kids_desc: "Pão, blend artesanal e queijo",

            section_porcoes_title: "Porções",
            item_feijao_title: "Feijão",
            item_pure_title: "Purê",
            item_arroz_branco_title: "Arroz branco",
            item_arroz_piamontese_title: "Arroz Piamontese",
            item_farofa_simples_title: "Farofa simples",
            item_farofa_banana_title: "Farofa de Banana",
            item_farofa_ovo_title: "Farofa de ovo",
            item_vinagrete_title: "Vinagrete",
            item_torrada_title: "Torrada",

            section_sobremesas_title: "Sobremesas",
            item_salada_frutas_solar_title: "Salada de Frutas Solar",
            item_salada_frutas_solar_desc: "Frutas da estação, iogurte natural e geleia de morango",
            item_pudim_leite_title: "Pudim de Leite",
            item_sufle_chocolate_title: "Suflê de Chocolate",
            item_sufle_chocolate_desc: "bolo quente, ganache de chocolate e morangos picados",
            item_brulee_cupuacu_title: "Brulée de Cupuaçú",
            item_brulee_cupuacu_desc: "Creme de cupuaçú com cobertura de casca brulée",
            item_duo_brownie_title: "Duo Brownie",
            item_duo_brownie_desc: "Brownie, sorvete de creme, creme de chocolate",
            item_tartelete_morango_title: "Tartelete de Morango",
            item_tartelete_morango_desc: "Casquinha crocante, creme de patissière, morango e chantilly",

            section_bebidas_title: "Bebidas",
            section_bebidas_subtitle_cervejas: "Cervejas",
            item_cervejas_list_title: "Tijuca Pilsen, Tijuca Puro Malte, Kroland e Silver",
            item_cerpa_export_title: "Cerpa Export",
            section_bebidas_subtitle_doses: "Doses",
            item_whisky_old_parr_title: "Whisky Old Parr",
            item_whisky_red_title: "Whisky Johnnie Walker Red",
            item_vodka_importada_title: "Vodka (Importada)",
            item_tequila_title: "Tequila",
            item_cointreau_title: "Cointreau",
            item_rum_title: "Rum",
            item_gin_title: "Gin",
            item_cachaca_jambu_title: "Cachaça de Jambú",
            section_bebidas_subtitle_nao_alcoolicos: "Não Alcoólicos",
            item_agua_sem_gas_title: "Água sem gás",
            item_agua_com_gas_title: "Água com gás",
            item_refrigerante_lata_title: "Refrigerante em lata",
            item_sucos_title: "Sucos (Consultar garçom)",
            item_shot_verde_solar_title: "Suco Verde do Solar",
            item_shot_limao_title: "Shot de limão",
            item_agua_tonica_title: "Água tônica Schweppes",
            item_agua_coco_title: "Água de coco (Consultar garçom)",
            item_energetico_title: "Energético Red Bull",
            item_milkshake_title: "Milkshake",
            item_milkshake_desc: "chocolate, morango e açaí",
            item_vitamina_title: "Vitamina",
            item_vitamina_desc: "mamão, banana e leite",
            item_cafe_expresso_title: "Café Expresso",

            footer_prohibit_smoking: "Proibido Fumar",
            footer_prohibit_coolers: "Proibido Cooler",
            footer_prohibit_pets: "Proibido Pet's",
            footer_prohibit_sound: "Proibido Caixa de Som",
            nav_cerpa: "Cervejas Cerpa",
            section_cerpa_title: "Espaço Cerpa",
            section_cerpa_subtitle: "Cervejas Premium da Nossa Patrocinadora Oficial",
            cerpa_badge_premium: "Premium",
            cerpa_badge_puro: "Puro Malte",
            cerpa_badge_refrescante: "Refrescante",
            cerpa_badge_gold: "Gold",
            cerpa_label_pairing: "Harmoniza com:",
            cerpa_label_temp: "Temperatura:",
            item_cerpa_export_title_sec: "Cerpa Export",
            item_cerpa_export_desc_sec: "A cerveja premium mais tradicional da Amazônia. Produzida com lúpulos especiais e água de altíssima pureza, possui corpo médio e sabor refinado.",
            item_cerpa_export_pairing: "Peixes grelhados, frutos do mar, salmão defumado e queijos leves.",
            item_tijuca_pilsen_title: "Tijuca Pilsen",
            item_tijuca_pilsen_desc: "Uma cerveja leve e de alta qualidade. Ideal para dias quentes na praia, trazendo suavidade perfeita e refrescância extrema.",
            item_tijuca_pilsen_pairing: "Isca de peixe crocante, batata frita, bolinhos e petiscos de praia.",
            item_tijuca_puromalte_title: "Tijuca Puro Malte",
            item_tijuca_puromalte_desc: "O equilíbrio perfeito entre refrescância e personalidade. Cerveja puro malte com mais corpo, mantendo o frescor carioca.",
            item_tijuca_puromalte_pairing: "Hambúrgueres artesanais, carnes na brasa e queijos de média cura.",
            item_cerpa_kroland_title: "Cerpa Kroland",
            item_cerpa_kroland_desc: "Uma autêntica puro malte de inspiração alemã. Leve e refrescante, com sabor equilibrado que une tradição à pureza amazônica.",
            item_cerpa_kroland_pairing: "Pastéis aperitivos, mandioca frita, batata frita e bolinhos de bacalhau.",
            cerpa_badge_gluten_free: "Sem Glúten",
            item_tijuca_silver_title: "Tijuca Silver",
            item_tijuca_silver_desc: "Cerveja premium sem glúten, leve e refrescante. A escolha perfeita para quem busca equilíbrio e sabor sem restrições.",
            item_tijuca_silver_pairing: "Peixes grelhados, saladas leves, petiscos e pratos suaves."
        },
        en: {
            nav_entradas: "Starters",
            nav_drinks: "Drinks",
            nav_saladas: "Salads",
            nav_mariscos: "Fish & Shrimp",
            nav_carnes: "Meats",
            nav_kids: "Kids",
            nav_caldos: "Soups",
            nav_burgers: "Burgers",
            nav_porcoes: "Portions",
            nav_sobremesas: "Desserts",
            nav_bebidas: "Beverages",
            nav_peixes: "Risotto & Pasta",
            sponsors_label: "Powered by",
            select_language: "Select your language",

            section_entradas_title: "To Start",
            section_entradas_subtitle: "(Starters)",
            item_bolinho_peixe_title: "Fish Cakes",
            item_bolinho_peixe_desc: "12 Units",
            item_camarao_empanado_title: "Breaded Shrimp",
            item_camarao_empanado_desc: "12 Units",
            item_camarao_alho_oleo_title: "Garlic and Oil Shrimp",
            item_camarao_alho_oleo_desc: "",
            item_batata_frita_title: "French Fries",
            item_batata_frita_desc: "Rosé sauce.",
            item_macaxeira_frita_title: "Fried Cassava",
            item_macaxeira_frita_desc: "",
            item_file_aperitivo_title: "Steak Strips with Banana Farofa",
            item_file_aperitivo_desc: "Steak strips with onions and banana cassava flour.",
            item_calabresa_acebolada_title: "Pepperoni with Onions",
            item_calabresa_acebolada_desc: "Served with cassava flour and toast",
            item_macaxeira_bacon_title: "Fried Cassava with Bacon",
            item_macaxeira_bacon_desc: "Rosé sauce.",
            item_caranguejo_refogado_title: "Sautéed Crab",
            item_caranguejo_refogado_desc: "Cassava flour.",
            item_camarao_crocante_title: "Crispy Shrimp",
            item_camarao_crocante_desc: "Breaded shrimp in special flour and rosé sauce.",
            item_panceta_porco_title: "Pork Belly",
            item_panceta_porco_desc: "Special roasted pork cut, gratinéed Portuguese pear and honey mustard.",
            item_ostra_fonduta_title: "Oysters with Cheese Fondue",
            item_ostra_fonduta_desc: "Gratinéed with parmesan cream, toast - 6 units.",
            item_carpaccio_pesto_title: "Carpaccio with Pesto",
            item_carpaccio_pesto_desc: "Thin slices of meat, pesto sauce, parmesan and toast.",
            item_isca_peixe_title: "Crispy Fish Strips",
            item_isca_peixe_desc: "Cassava flour and rosé sauce.",
            item_linguica_jambu_title: "Artisanal Sausage stuffed with Jambu",
            item_linguica_jambu_desc: "Grilled, served with tucupi pepper sauce, cassava flour and vinaigrette.",
            item_tabua_frios_title: "Cold Cuts Board",
            item_tabua_frios_desc: "Cheeses, salami, olive, grape, cream cheese and toast.",

            section_drinks_title: "Drinks",
            section_drinks_subtitle_autorais: "Signature Cocktails",
            tag_new: "(New)",

            item_o_barquinho_title: "O Barquinho",
            item_o_barquinho_desc: "Rum, Aperol, pineapple, sugar syrup and lemon.",
            item_macarico_title: "Maçarico",
            item_macarico_desc: "Jambu gin, Sicilian lemon, sugar syrup and angostura.",

            item_olho_grego_title: "Olho Grego",
            item_olho_grego_desc: "Gin, Blue Curacao, Sicilian lemon and ginger foam.",
            item_la_passion_title: "La Passion",
            item_la_passion_desc: "Vodka, strawberry, red pitaya, sugar and ice.",

            section_drinks_subtitle_atuais: "Modern Classics",
            item_moscow_mule_title: "Moscow Mule",
            item_moscow_mule_desc: "Vodka, Sicilian lemon, ginger syrup and ginger foam.",
            item_gin_mule_title: "Gin Mule",
            item_gin_mule_desc: "Gin, Sicilian lemon, ginger syrup and ginger foam.",
            item_gin_tonica_title: "Gin & Tonic",
            item_gin_tonica_desc: "Gin, tonic water and spice pairing.",
            item_spritz_aperol_title: "Aperol Spritz",
            item_spritz_aperol_desc: "Sparkling wine, Aperol and soda water.",
            item_mimosa_title: "Mimosa",
            item_mimosa_desc: "Sparkling wine and orange juice.",

            section_drinks_subtitle_antologicos: "Heritage Cocktails",
            item_negroni_title: "Negroni",
            item_negroni_desc: "Gin, vermouth, Campari and orange twist.",
            item_mojito_title: "Mojito",
            item_mojito_desc: "Rum, lemon and mint.",
            item_marguerita_title: "Margarita",
            item_marguerita_desc: "Tequila, Cointreau, Blue Curacao and Tahiti lemon.",

            item_caipirosca_title: "Caipirosca",
            item_caipirosca_desc: "Imported vodka, seasonal fruits, sugar and ice.",
            item_caipirinha_title: "Caipirinha",
            item_caipirinha_desc: "Cachaça, Tahiti lemon, sugar and ice.",
            item_coquetel_frutas_title: "Fruit Cocktail",
            item_coquetel_frutas_desc: "Fruit mix, vodka, condensed milk, cream, currant syrup and whipped cream.",

            section_drinks_subtitle_sem_alcool: "Non-Alcoholic",
            item_coquetel_frutas_sem_alcool_title: "Fruit Cocktail",
            item_coquetel_frutas_sem_alcool_desc: "Fruit mix, condensed milk, cream, currant syrup and whipped cream.",

            section_saladas_title: "Salads",
            item_salada_caesar_title: "Caesar Salad",
            item_salada_caesar_desc: "Mix of leaves, grilled chicken strips, croutons and parmesan with Caesar dressing.",
            item_salada_feijao_manteiguinha_title: "Bean Salad",
            item_salada_feijao_manteiguinha_desc: "Mix of leaves, 'manteiguinha' bean vinaigrette, tomato, carrot, zucchini and cheese.",

            section_mariscos_title: "Fish & Shrimp",
            item_pescada_tucupi_title: "Grilled Hake à la Tucupi Cream",
            item_pescada_tucupi_desc: "Rice with tucupi and jambu, and shrimp gravy",
            item_pescada_camarao_title: "Grilled Hake with Shrimp Sauce",
            item_pescada_camarao_desc: "White rice and mashed potatoes",
            item_camarao_solar_title: "Solar Crispy Shrimp",
            item_camarao_solar_desc: "Breaded and gratinéed with cheese, served with Piamontese rice and fries",
            item_caldeirada_pescada_title: "Yellow Hake Stew",
            item_caldeirada_pescada_desc: "Hake, shrimp, boiled egg, vegetables, white rice and gravy",
            item_peixe_frito_regional_title: "Regional Fried Fish",
            item_peixe_frito_regional_desc: "White rice, cassava flour mix and 'manteiguinha' bean vinaigrette",
            item_pescada_solar_title: "Solar Hake",
            item_pescada_solar_desc: "Breaded in special flour, creamy rice and mashed potatoes.",

            section_peixes_title: "Risotto & Pasta",
            item_peixe_amazonico_title: "Amazonian Fish in Garlic Crust",
            item_peixe_amazonico_desc: "Filhote fish, parmesan risotto and black olive sauce",
            item_espaguete_bolonhesa_title: "Spaghetti Bolognese",
            item_espaguete_bolonhesa_desc: "Single serving",

            section_carnes_title: "Meats",
            item_file_alfredo_title: "Filet Alfredo",
            item_file_alfredo_desc: "Grilled filet and fettuccine with parmesan cream and bacon aroma",
            item_file_solar_title: "Solar Filet",
            item_file_solar_desc: "Grilled with onion sauce, Piamontese rice, french fries and egg farofa",
            item_file_grelhado_solar_title: "Solar Grilled Filet",
            item_file_grelhado_solar_desc: "Grilled, rice, farofa and fries",

            section_kids_title: "Kids",
            item_file_cubinhos_title: "Filet Cubes",
            item_file_cubinhos_desc: "Grilled cubes, white rice, egg farofa and fries",
            item_isca_milanesa_title: "Breaded Fish Strips",
            item_isca_milanesa_desc: "Hake, white rice, farofa and mashed potatoes",

            section_caldos_title: "Soups & Broths",
            section_caldos_subtitle: "(single portion, served with toast)",
            item_sopa_caranguejo_title: "Crab Soup",
            item_canja_title: "Chicken Soup",
            item_caldo_legumes_title: "Vegetable Broth",
            item_caldo_tucupi_title: "Tucupi Broth",
            item_caldo_tucupi_desc: "Jambu and shrimp",

            section_burgers_title: "Burgers",
            section_burgers_subtitle: "Served with mixed leaf salad, tomato, grated carrot and red onion",
            item_file_do_reino_title: "Kingdom Filet",
            item_file_do_reino_desc: "Baguette bread, filet, kingdom cheese and fries",
            item_burger_solar_title: "Solar Burger",
            item_burger_solar_desc: "Bread, artisanal blend, cheese, pepperoni, egg and rustic potatoes",
            item_burger_kids_title: "Kids Burger",
            item_burger_kids_desc: "Bread, artisanal blend and cheese",

            section_porcoes_title: "Portions",
            item_feijao_title: "Beans",
            item_pure_title: "Mashed Potatoes",
            item_arroz_branco_title: "White Rice",
            item_arroz_piamontese_title: "Piamontese Rice",
            item_farofa_simples_title: "Simple Farofa",
            item_farofa_banana_title: "Banana Farofa",
            item_farofa_ovo_title: "Egg Farofa",
            item_vinagrete_title: "Vinaigrette",
            item_torrada_title: "Toast",

            section_sobremesas_title: "Desserts",
            item_salada_frutas_solar_title: "Solar Fruit Salad",
            item_salada_frutas_solar_desc: "Seasonal fruits, plain yogurt and strawberry jam",
            item_pudim_leite_title: "Milk Pudding",
            item_sufle_chocolate_title: "Chocolate Soufflé",
            item_sufle_chocolate_desc: "Warm cake, chocolate ganache and chopped strawberries",
            item_brulee_cupuacu_title: "Cupuaçu Brulée",
            item_brulee_cupuacu_desc: "Cupuaçu cream with brulée topping",
            item_duo_brownie_title: "Duo Brownie",
            item_duo_brownie_desc: "Brownie, vanilla ice cream, chocolate cream",
            item_tartelete_morango_title: "Strawberry Tartlet",
            item_tartelete_morango_desc: "Crispy shell, pastry cream, strawberry and whipped cream",

            section_bebidas_title: "Beverages",
            section_bebidas_subtitle_cervejas: "Beers",
            item_cervejas_list_title: "Tijuca Pilsen, Tijuca Puro Malte, Kroland and Silver",
            item_cerpa_export_title: "Cerpa Export",
            section_bebidas_subtitle_doses: "Shots",
            item_whisky_old_parr_title: "Likoz Old Parr",
            item_whisky_red_title: "Johnnie Walker Red Label",
            item_vodka_importada_title: "Vodka (Imported)",
            item_tequila_title: "Tequila",
            item_cointreau_title: "Cointreau",
            item_rum_title: "Rum",
            item_gin_title: "Gin",
            item_cachaca_jambu_title: "Jambu Cachaça",
            section_bebidas_subtitle_nao_alcoolicos: "Non-Alcoholic",
            item_agua_sem_gas_title: "Still Water",
            item_agua_com_gas_title: "Sparkling Water",
            item_refrigerante_lata_title: "Soft Drink (Can)",
            item_sucos_title: "Juices (Ask waiter)",
            item_shot_verde_solar_title: "Solar Green Juice",
            item_shot_limao_title: "Lemon Shot",
            item_agua_tonica_title: "Schweppes Tonic Water",
            item_agua_coco_title: "Coconut Water (Ask waiter)",
            item_energetico_title: "Red Bull Energy Drink",
            item_milkshake_title: "Milkshake",
            item_milkshake_desc: "Chocolate, strawberry and açaí",
            item_vitamina_title: "Vitamin Smoothie",
            item_vitamina_desc: "Papaya, banana and milk",
            item_cafe_expresso_title: "Espresso Coffee",

            footer_prohibit_smoking: "No Smoking",
            footer_prohibit_coolers: "No Coolers",
            footer_prohibit_pets: "No Pets",
            footer_prohibit_sound: "No Loudspeakers",
            nav_cerpa: "Cerpa Beers",
            section_cerpa_title: "Cerpa Lounge",
            section_cerpa_subtitle: "Premium Beers from Our Official Sponsor",
            cerpa_badge_premium: "Premium",
            cerpa_badge_puro: "Pure Malt",
            cerpa_badge_refrescante: "Refreshing",
            cerpa_badge_gold: "Gold",
            cerpa_label_pairing: "Pairs with:",
            cerpa_label_temp: "Temperature:",
            item_cerpa_export_title_sec: "Cerpa Export",
            item_cerpa_export_desc_sec: "The most traditional premium beer of the Amazon. Brewed with special hops and water of extreme purity, it features a medium body and refined taste.",
            item_cerpa_export_pairing: "Grilled fish, seafood, smoked salmon, and light cheeses.",
            item_tijuca_pilsen_title: "Tijuca Pilsen",
            item_tijuca_pilsen_desc: "A light and high-quality beer. Ideal for hot beach days, bringing perfect smoothness and extreme crispness.",
            item_tijuca_pilsen_pairing: "Crispy fish strips, french fries, croquettes, and beach snacks.",
            item_tijuca_puromalte_title: "Tijuca Puro Malte",
            item_tijuca_puromalte_desc: "The perfect balance between crispness and character. A pure malt beer with more body, keeping the refreshing Rio vibes.",
            item_tijuca_puromalte_pairing: "Artisanal burgers, grilled meats, and semi-cured cheeses.",
            item_cerpa_kroland_title: "Cerpa Kroland",
            item_cerpa_kroland_desc: "An authentic pure malt beer of German inspiration. Light and refreshing, with a balanced flavor that unites European tradition with Amazonian purity.",
            item_cerpa_kroland_pairing: "Appetizer pastries, fried cassava, french fries, and codfish croquettes.",
            cerpa_badge_gluten_free: "Gluten Free",
            item_tijuca_silver_title: "Tijuca Silver",
            item_tijuca_silver_desc: "Gluten-free premium beer, light and refreshing. The perfect choice for those seeking balance and flavor without restrictions.",
            item_tijuca_silver_pairing: "Grilled fish, light salads, snacks, and mild dishes."
        },
        fr: {
            nav_entradas: "Entrées",
            nav_drinks: "Boissons",
            nav_saladas: "Salades",
            nav_mariscos: "Poissons & Crevettes",
            nav_carnes: "Viandes",
            nav_kids: "Enfants",
            nav_caldos: "Soupes",
            nav_burgers: "Burgers",
            nav_porcoes: "Portions",
            nav_sobremesas: "Desserts",
            nav_bebidas: "Boissons",
            nav_peixes: "Risotto & Pâtes",
            sponsors_label: "Offert par",
            select_language: "Choisissez votre langue",

            section_entradas_title: "Pour Commencer",
            section_entradas_subtitle: "(Entrées)",
            item_bolinho_peixe_title: "Croquettes de Poisson",
            item_bolinho_peixe_desc: "12 Unités",
            item_camarao_empanado_title: "Crevettes Panées",
            item_camarao_empanado_desc: "12 Unités",
            item_camarao_alho_oleo_title: "Crevettes à l'Ail et à l'Huile",
            item_camarao_alho_oleo_desc: "",
            item_batata_frita_title: "Frites",
            item_batata_frita_desc: "Sauce Rosé.",
            item_macaxeira_frita_title: "Manioc Frit",
            item_macaxeira_frita_desc: "",
            item_file_aperitivo_title: "Lanières de Filet à la Farofa de Banane",
            item_file_aperitivo_desc: "Lanières de filet aux oignons et farine de manioc à la banane.",
            item_calabresa_acebolada_title: "Saucisse Calabresa aux Oignons",
            item_calabresa_acebolada_desc: "Servi avec farine de manioc et toasts",
            item_macaxeira_bacon_title: "Manioc Frit au Bacon",
            item_macaxeira_bacon_desc: "Sauce Rosé.",
            item_caranguejo_refogado_title: "Crabe Sauté",
            item_caranguejo_refogado_desc: "Farine de Manioc.",
            item_camarao_crocante_title: "Crevettes Croustillantes",
            item_camarao_crocante_desc: "Crevettes panées dans une farine spéciale et sauce rosé.",
            item_panceta_porco_title: "Poitrine de Porc",
            item_panceta_porco_desc: "Coupe de porc spéciale rôtie, poire portugaise gratinée et moutarde au miel.",
            item_ostra_fonduta_title: "Huîtres à la Fondue de Fromage",
            item_ostra_fonduta_desc: "Gratinées à la crème de parmesan, toasts - 6 unités.",
            item_carpaccio_pesto_title: "Carpaccio au Pesto",
            item_carpaccio_pesto_desc: "Fines tranches de viande, sauce pesto, parmesan et toasts.",
            item_isca_peixe_title: "Lanières de Poisson Croustillantes",
            item_isca_peixe_desc: "Farine de manioc et sauce rosé.",
            item_linguica_jambu_title: "Saucisse Artisanale farcie au Jambu",
            item_linguica_jambu_desc: "Grillée, servie avec sauce pimentée au tucupi, farine de manioc et vinaigrette.",
            item_tabua_frios_title: "Planche de Charcuterie",
            item_tabua_frios_desc: "Fromages, salami, olive, raisin, fromage à la crème et toasts.",

            section_drinks_title: "Boissons",
            section_drinks_subtitle_autorais: "Cocktails Signature",
            tag_new: "(Nouveau)",

            item_o_barquinho_title: "O Barquinho",
            item_o_barquinho_desc: "Rhum, Aperol, ananas, sirop de sucre et citron.",
            item_macarico_title: "Maçarico",
            item_macarico_desc: "Gin au jambu, citron sicilien, sirop de sucre et angostura.",

            item_olho_grego_title: "Olho Grego",
            item_olho_grego_desc: "Gin, Curacao Bleu, citron sicilien et mousse de gingembre.",
            item_la_passion_title: "La Passion",
            item_la_passion_desc: "Vodka, fraise, pitaya rouge, sucre et glace.",

            section_drinks_subtitle_atuais: "Classiques Modernes",
            item_moscow_mule_title: "Moscow Mule",
            item_moscow_mule_desc: "Vodka, citron sicilien, sirop de gingembre et mousse de gingembre.",
            item_gin_mule_title: "Gin Mule",
            item_gin_mule_desc: "Gin, citron sicilien, sirop de gingembre et mousse de gingembre.",
            item_gin_tonica_title: "Gin Tonic",
            item_gin_tonica_desc: "Gin, eau tonique et épices.",
            item_spritz_aperol_title: "Aperol Spritz",
            item_spritz_aperol_desc: "Vin mousseux, Aperol et eau gazeuse.",
            item_mimosa_title: "Mimosa",
            item_mimosa_desc: "Vin mousseux et jus d'orange.",

            section_drinks_subtitle_antologicos: "Cocktails Héritage",
            item_negroni_title: "Negroni",
            item_negroni_desc: "Gin, vermouth, Campari et zeste d'orange.",
            item_mojito_title: "Mojito",
            item_mojito_desc: "Rhum, citron et menthe.",
            item_marguerita_title: "Margarita",
            item_marguerita_desc: "Tequila, Cointreau, Curacao Bleu et citron vert.",

            item_caipirosca_title: "Caipirosca",
            item_caipirosca_desc: "Vodka importée, fruits de saison, sucre et glace.",
            item_caipirinha_title: "Caipirinha",
            item_caipirinha_desc: "Cachaça, citron vert, sucre et glace.",
            item_coquetel_frutas_title: "Cocktail de Fruits",
            item_coquetel_frutas_desc: "Mélange de fruits, vodka, lait concentré, crème, sirop de groseille et chantilly.",

            section_drinks_subtitle_sem_alcool: "Sans Alcool",
            item_coquetel_frutas_sem_alcool_title: "Cocktail de Fruits",
            item_coquetel_frutas_sem_alcool_desc: "Mélange de fruits, lait concentré, crème, sirop de groseille et chantilly.",

            section_saladas_title: "Salades",
            item_salada_caesar_title: "Salade Caesar",
            item_salada_caesar_desc: "Mélange de feuilles, lanières de poulet grillé, croûtons et parmesan avec sauce Caesar.",
            item_salada_feijao_manteiguinha_title: "Salade de Haricots",
            item_salada_feijao_manteiguinha_desc: "Mélange de feuilles, vinaigrette de haricots 'manteiguinha', tomate, carotte, courgette et fromage.",

            section_mariscos_title: "Poissons & Crevettes",
            item_pescada_tucupi_title: "Merlu Grillé à la Crème de Tucupi",
            item_pescada_tucupi_desc: "Riz au tucupi et jambu, et sauce aux crevettes",
            item_pescada_camarao_title: "Merlu Grillé à la Sauce aux Crevettes",
            item_pescada_camarao_desc: "Riz blanc et purée de pommes de terre",
            item_camarao_solar_title: "Crevettes Croustillantes Solar",
            item_camarao_solar_desc: "Panées et gratinées au fromage, servies avec riz Piamontese et frites",
            item_caldeirada_pescada_title: "Ragoût de Merlu Jaune",
            item_caldeirada_pescada_desc: "Merlu, crevettes, œuf dur, légumes, riz blanc et sauce",
            item_peixe_frito_regional_title: "Poisson Frit Régional",
            item_peixe_frito_regional_desc: "Riz blanc, mélange de farine de manioc et vinaigrette de haricots",
            item_pescada_solar_title: "Merlu Solar",
            item_pescada_solar_desc: "Pané dans une farine spéciale, riz crémeux et purée de pommes de terre.",

            section_peixes_title: "Risotto & Pâtes",
            item_peixe_amazonico_title: "Poisson Amazonien en Croûte d'Ail",
            item_peixe_amazonico_desc: "Poisson Filhote, risotto au parmesan et sauce aux olives noires",
            item_espaguete_bolonhesa_title: "Spaghetti Bolognaise",
            item_espaguete_bolonhesa_desc: "Portion individuelle",

            section_carnes_title: "Viandes",
            item_file_alfredo_title: "Filet Alfredo",
            item_file_alfredo_desc: "Filet grillé et fettuccine à la crème de parmesan et arôme de bacon",
            item_file_solar_title: "Filet Solar",
            item_file_solar_desc: "Grillé avec sauce aux oignons, riz Piamontese, frites et farofa aux œufs",
            item_file_grelhado_solar_title: "Filet Grillé Solar",
            item_file_grelhado_solar_desc: "Grillé, riz, farofa et frites",

            section_kids_title: "Enfants",
            item_file_cubinhos_title: "Cubes de Filet",
            item_file_cubinhos_desc: "Cubes grillés, riz blanc, farofa aux œufs et frites",
            item_isca_milanesa_title: "Lanières de Poisson Panées",
            item_isca_milanesa_desc: "Merlu, riz blanc, farofa et purée de pommes de terre",

            section_caldos_title: "Soupes & Bouillons",
            section_caldos_subtitle: "(portion individuelle, servie avec toasts)",
            item_sopa_caranguejo_title: "Soupe de Crabe",
            item_canja_title: "Soupe de Poulet",
            item_caldo_legumes_title: "Bouillon de Légumes",
            item_caldo_tucupi_title: "Bouillon de Tucupi",
            item_caldo_tucupi_desc: "Jambu et crevettes",

            section_burgers_title: "Burgers",
            section_burgers_subtitle: "Servi avec salade de feuilles mixtes, tomate, carotte râpée et oignon rouge",
            item_file_do_reino_title: "Filet du Royaume",
            item_file_do_reino_desc: "Pain baguette, filet, fromage du royaume et frites",
            item_burger_solar_title: "Burger Solar",
            item_burger_solar_desc: "Pain, mélange artisanal, fromage, pepperoni, œuf et pommes de terre rustiques",
            item_burger_kids_title: "Burger Enfants",
            item_burger_kids_desc: "Pain, mélange artisanal et fromage",

            section_porcoes_title: "Portions",
            item_feijao_title: "Haricots",
            item_pure_title: "Purée de Pommes de Terre",
            item_arroz_branco_title: "Riz Blanc",
            item_arroz_piamontese_title: "Riz Piamontese",
            item_farofa_simples_title: "Farofa Simple",
            item_farofa_banana_title: "Farofa à la Banane",
            item_farofa_ovo_title: "Farofa aux Œufs",
            item_vinagrete_title: "Vinaigrette",
            item_torrada_title: "Toasts",

            section_sobremesas_title: "Desserts",
            item_salada_frutas_solar_title: "Salade de Fruits Solar",
            item_salada_frutas_solar_desc: "Fruits de saison, yaourt nature et confiture de fraise",
            item_pudim_leite_title: "Flan au Lait",
            item_sufle_chocolate_title: "Soufflé au Chocolat",
            item_sufle_chocolate_desc: "Gâteau chaud, ganache au chocolat et fraises coupées",
            item_brulee_cupuacu_title: "Brulée de Cupuaçu",
            item_brulee_cupuacu_desc: "Crème de Cupuaçu avec couverture brulée",
            item_duo_brownie_title: "Duo Brownie",
            item_duo_brownie_desc: "Brownie, glace vanille, crème au chocolat",
            item_tartelete_morango_title: "Tartelette aux Fraises",
            item_tartelete_morango_desc: "Coque croustillante, crème pâtissière, fraise et chantilly",

            section_bebidas_title: "Boissons",
            section_bebidas_subtitle_cervejas: "Bières",
            item_cervejas_list_title: "Tijuca Pilsen, Tijuca Puro Malte, Kroland et Silver",
            item_cerpa_export_title: "Cerpa Export",
            section_bebidas_subtitle_doses: "Shots",
            item_whisky_old_parr_title: "Likoz Old Parr",
            item_whisky_red_title: "Johnnie Walker Red Label",
            item_vodka_importada_title: "Vodka (Importée)",
            item_tequila_title: "Tequila",
            item_cointreau_title: "Cointreau",
            item_rum_title: "Rhum",
            item_gin_title: "Gin",
            item_cachaca_jambu_title: "Cachaça de Jambu",
            section_bebidas_subtitle_nao_alcoolicos: "Sans Alcool",
            item_agua_sem_gas_title: "Eau Plate",
            item_agua_com_gas_title: "Eau Gazeuse",
            item_refrigerante_lata_title: "Soda (Canette)",
            item_sucos_title: "Jus (Demander au serveur)",
            item_shot_verde_solar_title: "Jus Vert Solar",
            item_shot_limao_title: "Shot de Citron",
            item_agua_tonica_title: "Eau Tonique Schweppes",
            item_agua_coco_title: "Eau de Coco (Demander au serveur)",
            item_energetico_title: "Boisson Énergisante Red Bull",
            item_milkshake_title: "Milkshake",
            item_milkshake_desc: "Chocolat, fraise et açaí",
            item_vitamina_title: "Smoothie Vitaminé",
            item_vitamina_desc: "Papaye, banane et lait",
            item_cafe_expresso_title: "Café Expresso",

            footer_prohibit_smoking: "Interdit de Fumer",
            footer_prohibit_coolers: "Glacières Interdites",
            footer_prohibit_pets: "Animaux Interdits",
            footer_prohibit_sound: "Enceintes Interdites",
            nav_cerpa: "Bières Cerpa",
            section_cerpa_title: "Espace Cerpa",
            section_cerpa_subtitle: "Bières Premium de Notre Partenaire Officiel",
            cerpa_badge_premium: "Premium",
            cerpa_badge_puro: "Pur Malt",
            cerpa_badge_refrescante: "Rafraîchissante",
            cerpa_badge_gold: "Gold",
            cerpa_label_pairing: "S'accorde avec:",
            cerpa_label_temp: "Température:",
            item_cerpa_export_title_sec: "Cerpa Export",
            item_cerpa_export_desc_sec: "La bière premium la plus traditionnelle d'Amazonie. Brassée avec des houblons spéciaux et une eau d'une pureté extrême, elle offre un corps moyen et un goût raffiné.",
            item_cerpa_export_pairing: "Poissons grillés, fruits de mer, saumon fumé et fromages doux.",
            item_tijuca_pilsen_title: "Tijuca Pilsen",
            item_tijuca_pilsen_desc: "Une bière légère et de haute qualité. Idéale pour les journées chaudes à la plage, apportant une douceur parfaite et une fraîcheur extrême.",
            item_tijuca_pilsen_pairing: "Lanières de poisson croustillantes, frites, croquettes et collations de plage.",
            item_tijuca_puromalte_title: "Tijuca Puro Malte",
            item_tijuca_puromalte_desc: "L'équilibre parfait entre fraîcheur et caractère. Une bière pur malt plus corsée, tout en conservant la fraîcheur de Rio.",
            item_tijuca_puromalte_pairing: "Burgers artisanaux, viandes grillées et fromages à pâte demi-ferme.",
            item_cerpa_kroland_title: "Cerpa Kroland",
            item_cerpa_kroland_desc: "Une authentique bière pur malt d'inspiration allemande. Légère et rafraîchissante, avec une saveur équilibrée qui unit la tradition européenne à la pureté de l'Amazonie.",
            item_cerpa_kroland_pairing: "Beignets apéritifs, manioc frit, frites et croquettes de morue.",
            item_cerpa_gold_title_sec: "Cerpa Gold",
            item_cerpa_gold_desc: "Une bière classique, légère et extrêmement savoureuse, idéale pour les moments de détente et pour lutter contre la chaleur.",
            item_cerpa_gold_pairing: "Portions d'amuse-gueules assorties, frites et salades fraîches.",
            cerpa_badge_gluten_free: "Sans Gluten",
            item_tijuca_silver_title: "Tijuca Silver",
            item_tijuca_silver_desc: "Bière premium sans gluten, légère et rafraîchissante. Le choix idéal pour ceux qui recherchent équilibre et saveur sans restrictions.",
            item_tijuca_silver_pairing: "Poissons grillés, salades légères, amuse-gueules et plats doux."
        },
        it: {
            nav_entradas: "Antipasti",
            nav_drinks: "Drink",
            nav_saladas: "Insalate",
            nav_mariscos: "Pesce & Gamberi",
            nav_carnes: "Carni",
            nav_kids: "Bambini",
            nav_caldos: "Zuppe",
            nav_burgers: "Hamburger",
            nav_porcoes: "Porzioni",
            nav_sobremesas: "Dolci",
            nav_bebidas: "Bevande",
            nav_peixes: "Risotto & Pasta",
            sponsors_label: "Offerto da",
            select_language: "Scegli la tua lingua",

            section_entradas_title: "Per Iniziare",
            section_entradas_subtitle: "(Antipasti)",
            item_bolinho_peixe_title: "Polpette di Pesce",
            item_bolinho_peixe_desc: "12 Pezzi",
            item_camarao_empanado_title: "Gamberi Impanati",
            item_camarao_empanado_desc: "12 Pezzi",
            item_camarao_alho_oleo_title: "Gamberi Aglio e Olio",
            item_camarao_alho_oleo_desc: "",
            item_batata_frita_title: "Patatine Fritte",
            item_batata_frita_desc: "Salsa Rosa.",
            item_macaxeira_frita_title: "Manioca Fritta",
            item_macaxeira_frita_desc: "",
            item_file_aperitivo_title: "Straccetti di Filetto con Farofa di Banana",
            item_file_aperitivo_desc: "Straccetti di filetto con cipolle e farina di manioca alla banana.",
            item_calabresa_acebolada_title: "Salsiccia Calabresa con Cipolle",
            item_calabresa_acebolada_desc: "Servita con farofa e pane tostato",
            item_macaxeira_bacon_title: "Manioca Fritta con Pancetta",
            item_macaxeira_bacon_desc: "Salsa Rosa.",
            item_caranguejo_refogado_title: "Granchio Saltato",
            item_caranguejo_refogado_desc: "Farofa.",
            item_camarao_crocante_title: "Gamberi Croccanti",
            item_camarao_crocante_desc: "Gamberi impanati in farina speciale e salsa rosa.",
            item_panceta_porco_title: "Pancia di Maiale",
            item_panceta_porco_desc: "Taglio di maiale speciale arrosto, pera portoghese gratinata e senape al miele.",
            item_ostra_fonduta_title: "Ostriche con Fonduta di Formaggio",
            item_ostra_fonduta_desc: "Gratinate alla crema di parmigiano, crostini - 6 unità.",
            item_carpaccio_pesto_title: "Carpaccio al Pesto",
            item_carpaccio_pesto_desc: "Fettine sottili di carne, salsa al pesto, parmigiano e crostini.",
            item_isca_peixe_title: "Bastoncini di Pesce Croccanti",
            item_isca_peixe_desc: "Farofa e salsa rosa.",
            item_linguica_jambu_title: "Salsiccia Artigianale ripiena di Jambu",
            item_linguica_jambu_desc: "Grigliata, servita con salsa al peperoncino tucupi, farofa e vinaigrette.",
            item_tabua_frios_title: "Tagliere di Salumi e Formaggi",
            item_tabua_frios_desc: "Formaggi, salame, oliva, uva, crema di formaggio e crostini.",

            section_drinks_title: "Drink",
            section_drinks_subtitle_autorais: "Cocktail d'Autore",
            tag_new: "(Nuovo)",

            item_o_barquinho_title: "O Barquinho",
            item_o_barquinho_desc: "Rum, Aperol, ananas, sciroppo di zucchero e limone.",
            item_macarico_title: "Maçarico",
            item_macarico_desc: "Gin al jambu, limone siciliano, sciroppo di zucchero e angostura.",

            item_olho_grego_title: "Olho Grego",
            item_olho_grego_desc: "Gin, Blue Curacao, limone siciliano e schiuma di zenzero.",
            item_la_passion_title: "La Passion",
            item_la_passion_desc: "Vodka, fragola, pitaya rossa, zucchero e ghiaccio.",

            section_drinks_subtitle_atuais: "Classici Moderni",
            item_moscow_mule_title: "Moscow Mule",
            item_moscow_mule_desc: "Vodka, limone siciliano, sciroppo di zenzero e schiuma di zenzero.",
            item_gin_mule_title: "Gin Mule",
            item_gin_mule_desc: "Gin, limone siciliano, sciroppo di zenzero e schiuma di zenzero.",
            item_gin_tonica_title: "Gin Tonic",
            item_gin_tonica_desc: "Gin, acqua tonica e spezie.",
            item_spritz_aperol_title: "Aperol Spritz",
            item_spritz_aperol_desc: "Spumante, Aperol e soda.",
            item_mimosa_title: "Mimosa",
            item_mimosa_desc: "Spumante e succo d'arancia.",

            section_drinks_subtitle_antologicos: "Cocktail Storici",
            item_negroni_title: "Negroni",
            item_negroni_desc: "Gin, vermouth, Campari e scorza d'arancia.",
            item_mojito_title: "Mojito",
            item_mojito_desc: "Rum, limone e menta.",
            item_marguerita_title: "Margarita",
            item_marguerita_desc: "Tequila, Cointreau, Blue Curacao e lime.",

            item_caipirosca_title: "Caipirosca",
            item_caipirosca_desc: "Vodka importata, frutta di stagione, zucchero e ghiaccio.",
            item_caipirinha_title: "Caipirinha",
            item_caipirinha_desc: "Cachaça, lime, zucchero e ghiaccio.",
            item_coquetel_frutas_title: "Cocktail di Frutta",
            item_coquetel_frutas_desc: "Mix di frutta, vodka, latte condensato, panna, sciroppo di ribes e panna montata.",

            section_drinks_subtitle_sem_alcool: "Analcolici",
            item_coquetel_frutas_sem_alcool_title: "Cocktail di Frutta",
            item_coquetel_frutas_sem_alcool_desc: "Mix di frutta, latte condensato, panna, sciroppo di ribes e panna montata.",

            section_saladas_title: "Insalate",
            item_salada_caesar_title: "Caesar Salad",
            item_salada_caesar_desc: "Mix di foglie, straccetti di pollo grigliato, crostini e parmigiano con salsa Caesar.",
            item_salada_feijao_manteiguinha_title: "Insalata di Fagioli",
            item_salada_feijao_manteiguinha_desc: "Mix di foglie, vinaigrette di fagioli 'manteiguinha', pomodoro, carota, zucchine e formaggio.",

            section_mariscos_title: "Pesce & Gamberi",
            item_pescada_tucupi_title: "Merluzzo Grigliato alla Crema di Tucupi",
            item_pescada_tucupi_desc: "Riso al tucupi e jambu, e salsa di gamberi",
            item_pescada_camarao_title: "Merluzzo Grigliato con Salsa di Gamberi",
            item_pescada_camarao_desc: "Riso bianco e purè di patate",
            item_camarao_solar_title: "Gamberi Croccanti Solar",
            item_camarao_solar_desc: "Impanati e gratinati al formaggio, serviti con riso Piamontese e patatine",
            item_caldeirada_pescada_title: "Zuppa di Merluzzo Giallo",
            item_caldeirada_pescada_desc: "Merluzzo, gamberi, uovo sodo, verdure, riso bianco e salsa",
            item_peixe_frito_regional_title: "Pesce Fritto Regionale",
            item_peixe_frito_regional_desc: "Riso bianco, farofa e vinaigrette di fagioli",
            item_pescada_solar_title: "Merluzzo Solar",
            item_pescada_solar_desc: "Impanato in farina speciale, riso cremoso e purè di patate.",

            section_peixes_title: "Risotto & Pasta",
            item_peixe_amazonico_title: "Pesce Amazzonico in Crosta d'Aglio",
            item_peixe_amazonico_desc: "Pesce Filhote, risotto al parmigiano e salsa di olive nere",
            item_espaguete_bolonhesa_title: "Spaghetti alla Bolognese",
            item_espaguete_bolonhesa_desc: "Porzione singola",

            section_carnes_title: "Carni",
            item_file_alfredo_title: "Filetto Alfredo",
            item_file_alfredo_desc: "Filetto grigliato e fettuccine alla crema di parmigiano e aroma di pancetta",
            item_file_solar_title: "Filetto Solar",
            item_file_solar_desc: "Grigliato con salsa di cipolle, riso Piamontese, patatine fritte e farofa all'uovo",
            item_file_grelhado_solar_title: "Filetto Grigliato Solar",
            item_file_grelhado_solar_desc: "Grigliato, riso, farofa e patatine",

            section_kids_title: "Bambini",
            item_file_cubinhos_title: "Cubetti di Filetto",
            item_file_cubinhos_desc: "Cubetti grigliati, riso bianco, farofa all'uovo e patatine",
            item_isca_milanesa_title: "Bastoncini di Pesce Impanati",
            item_isca_milanesa_desc: "Merluzzo, riso bianco, farofa e purè di patate",

            section_caldos_title: "Zuppe & Brodi",
            section_caldos_subtitle: "(porzione singola, servita con crostini)",
            item_sopa_caranguejo_title: "Zuppa di Granchio",
            item_canja_title: "Zuppa di Pollo",
            item_caldo_legumes_title: "Brodo Vegetale",
            item_caldo_tucupi_title: "Brodo di Tucupi",
            item_caldo_tucupi_desc: "Jambu e gamberi",

            section_burgers_title: "Hamburger",
            section_burgers_subtitle: "Servito con insalata mista, pomodoro, carota grattugiata e cipolla rossa",
            item_file_do_reino_title: "Filetto Reale",
            item_file_do_reino_desc: "Baguette, filetto, formaggio del regno e patatine",
            item_burger_solar_title: "Burger Solar",
            item_burger_solar_desc: "Pane, mix artigianale, formaggio, salsiccia, uovo e patate rustiche",
            item_burger_kids_title: "Burger Bambini",
            item_burger_kids_desc: "Pane, mix artigianale e formaggio",

            section_porcoes_title: "Porzioni",
            item_feijao_title: "Fagioli",
            item_pure_title: "Purè di Patate",
            item_arroz_branco_title: "Riso Bianco",
            item_arroz_piamontese_title: "Riso Piamontese",
            item_farofa_simples_title: "Farofa Semplice",
            item_farofa_banana_title: "Farofa alla Banana",
            item_farofa_ovo_title: "Farofa all'Uovo",
            item_vinagrete_title: "Vinaigrette",
            item_torrada_title: "Pane Tostato",

            section_sobremesas_title: "Dolci",
            item_salada_frutas_solar_title: "Insalata di Frutta Solar",
            item_salada_frutas_solar_desc: "Frutta di stagione, yogurt naturale e marmellata di fragole",
            item_pudim_leite_title: "Budino di Latte",
            item_sufle_chocolate_title: "Soufflé al Cioccolato",
            item_sufle_chocolate_desc: "Torta calda, ganache al cioccolato e fragole tritate",
            item_brulee_cupuacu_title: "Brulée di Cupuaçu",
            item_brulee_cupuacu_desc: "Crema di Cupuaçu con copertura brulée",
            item_duo_brownie_title: "Duo Brownie",
            item_duo_brownie_desc: "Brownie, gelato alla vaniglia, crema al cioccolato",
            item_tartelete_morango_title: "Tartelletta alla Fragola",
            item_tartelete_morango_desc: "Guscio croccante, crema pasticcera, fragola e panna montata",

            section_bebidas_title: "Bevande",
            section_bebidas_subtitle_cervejas: "Birre",
            item_cervejas_list_title: "Tijuca Pilsen, Tijuca Puro Malte, Kroland e Silver",
            item_cerpa_export_title: "Cerpa Export",
            section_bebidas_subtitle_doses: "Shot",
            item_whisky_old_parr_title: "Likoz Old Parr",
            item_whisky_red_title: "Johnnie Walker Red Label",
            item_vodka_importada_title: "Vodka (Importata)",
            item_tequila_title: "Tequila",
            item_cointreau_title: "Cointreau",
            item_rum_title: "Rum",
            item_gin_title: "Gin",
            item_cachaca_jambu_title: "Cachaça di Jambu",
            section_bebidas_subtitle_nao_alcoolicos: "Analcolici",
            item_agua_sem_gas_title: "Acqua Naturale",
            item_agua_com_gas_title: "Acqua Frizzante",
            item_refrigerante_lata_title: "Bibita (Lattina)",
            item_sucos_title: "Succhi (Chiedere al cameriere)",
            item_shot_verde_solar_title: "Succo Verde Solar",
            item_shot_limao_title: "Shot di Limone",
            item_agua_tonica_title: "Acqua Tonica Schweppes",
            item_agua_coco_title: "Acqua di Cocco (Chiedere al cameriere)",
            item_energetico_title: "Energy Drink Red Bull",
            item_milkshake_title: "Milkshake",
            item_milkshake_desc: "Cioccolato, fragola e açaí",
            item_vitamina_title: "Frullato Vitaminico",
            item_vitamina_desc: "Papaya, banana e latte",
            item_cafe_expresso_title: "Caffè Espresso",

            footer_prohibit_smoking: "Vietato Fumare",
            footer_prohibit_coolers: "Vietato Introdurre Ghiacciaie",
            footer_prohibit_pets: "Vietati gli Animali",
            footer_prohibit_sound: "Vietati gli Altoparlanti",
            nav_cerpa: "Birre Cerpa",
            section_cerpa_title: "Spazio Cerpa",
            section_cerpa_subtitle: "Birre Premium del Nostro Sponsor Ufficiale",
            cerpa_badge_premium: "Premium",
            cerpa_badge_puro: "Puro Malto",
            cerpa_badge_refrescante: "Rinfrescante",
            cerpa_badge_gold: "Gold",
            cerpa_label_pairing: "Si abbina con:",
            cerpa_label_temp: "Temperatura:",
            item_cerpa_export_title_sec: "Birra Cerpa Export",
            item_cerpa_export_desc_sec: "La birra premium più tradizionale dell'Amazzonia. Prodotta con luppoli speciali e acqua di altissima purezza, ha un corpo medio e un gusto raffinato.",
            item_cerpa_export_pairing: "Pesce alla griglia, frutti di mare, salmone affumicato e formaggi leggeri.",
            item_tijuca_pilsen_title: "Tijuca Pilsen",
            item_tijuca_pilsen_desc: "Una birra leggera e di alta qualità. Ideale per le calde giornate in spiaggia, regala una perfetta morbidezza ed estrema freschezza.",
            item_tijuca_pilsen_pairing: "Bastoncini di pesce croccanti, patatine fritte, polpettine e snack da spiaggia.",
            item_tijuca_puromalte_title: "Tijuca Puro Malte",
            item_tijuca_puromalte_desc: "Il perfetto equilibrio tra freschezza e personalità. Una birra a puro malto con più corpo, mantenendo la freschezza di Rio.",
            item_tijuca_puromalte_pairing: "Hamburger artigianali, carni alla griglia e formaggi a media stagionatura.",
            item_cerpa_kroland_title: "Cerpa Kroland",
            item_cerpa_kroland_desc: "Un'autentica birra puro malto di ispirazione tedesca. Leggera e rinfrescante, con un sapore equilibrato che unisce la tradizione europea alla purezza dell'Amazzonia.",
            item_cerpa_kroland_pairing: "Pasticcini salati, manioca fritta, patatine fritte e crocchette di baccalà.",
            item_cerpa_gold_title_sec: "Cerpa Gold",
            item_cerpa_gold_desc: "Una birra classica, leggera ed estremamente gustosa, ideale per momenti rilassanti e per combattere il caldo.",
            item_cerpa_gold_pairing: "Porzioni di stuzzichini assortiti, patatine fritte e insalate fresche.",
            cerpa_badge_gluten_free: "Senza Glutine",
            item_tijuca_silver_title: "Tijuca Silver",
            item_tijuca_silver_desc: "Birra premium senza glutine, leggera e rinfrescante. La scelta ideale per chi cerca equilibrio e gusto senza restrizioni.",
            item_tijuca_silver_pairing: "Pesce alla griglia, insalate leggere, snack e piatti delicati."
        },
        es: {
            nav_entradas: "Entradas",
            nav_drinks: "Bebidas",
            nav_saladas: "Ensaladas",
            nav_mariscos: "Pescado y Camarones",
            nav_carnes: "Carnes",
            nav_kids: "Niños",
            nav_caldos: "Sopas",
            nav_burgers: "Hamburguesas",
            nav_porcoes: "Porciones",
            nav_sobremesas: "Postres",
            nav_bebidas: "Bebidas",
            nav_peixes: "Risotto y Pasta",
            sponsors_label: "Ofrecido por",
            select_language: "Elige tu idioma",

            section_entradas_title: "Para Empezar",
            section_entradas_subtitle: "(Entradas)",
            item_bolinho_peixe_title: "Croquetas de Pescado",
            item_bolinho_peixe_desc: "12 Unidades",
            item_camarao_empanado_title: "Camarones Empanizados",
            item_camarao_empanado_desc: "12 Unidades",
            item_camarao_alho_oleo_title: "Camarones al Ajillo",
            item_camarao_alho_oleo_desc: "",
            item_batata_frita_title: "Papas Fritas",
            item_batata_frita_desc: "Salsa Rosada.",
            item_macaxeira_frita_title: "Yuca Frita",
            item_macaxeira_frita_desc: "",
            item_file_aperitivo_title: "Tiras de Filete con Farofa de Plátano",
            item_file_aperitivo_desc: "Tiras de filete con cebolla y harina de yuca con plátano.",
            item_calabresa_acebolada_title: "Salchicha Calabresa Encebollada",
            item_calabresa_acebolada_desc: "Servida con harina de yuca y tostadas",
            item_macaxeira_bacon_title: "Yuca Frita con Tocino",
            item_macaxeira_bacon_desc: "Salsa Rosada.",
            item_caranguejo_refogado_title: "Cangrejo Salteado",
            item_caranguejo_refogado_desc: "Harina de Yuca.",
            item_camarao_crocante_title: "Camarones Crujientes",
            item_camarao_crocante_desc: "Camarones empanizados en harina especial y salsa rosada.",
            item_panceta_porco_title: "Panceta de Cerdo",
            item_panceta_porco_desc: "Corte de cerdo especial asado, pera portuguesa gratinada y mostaza con miel.",
            item_ostra_fonduta_title: "Ostras con Fondue de Queso",
            item_ostra_fonduta_desc: "Gratinadas con crema de parmesano, tostadas - 6 unidades.",
            item_carpaccio_pesto_title: "Carpaccio al Pesto",
            item_carpaccio_pesto_desc: "Láminas finas de carne, salsa pesto, parmesano y tostadas.",
            item_isca_peixe_title: "Tiras de Pescado Crujientes",
            item_isca_peixe_desc: "Harina de yuca y salsa rosada.",
            item_linguica_jambu_title: "Salchicha Artesanal rellena de Jambu",
            item_linguica_jambu_desc: "A la parrilla, servida con salsa de pimienta tucupi, harina de yuca y vinagreta.",
            item_tabua_frios_title: "Tabla de Fiambres",
            item_tabua_frios_desc: "Quesos, salami, aceituna, uva, crema de queso y tostadas.",

            section_drinks_title: "Bebidas",
            section_drinks_subtitle_autorais: "Cócteles de Autor",
            tag_new: "(Nuevo)",

            item_o_barquinho_title: "O Barquinho",
            item_o_barquinho_desc: "Ron, Aperol, piña, jarabe de azúcar y limón.",
            item_macarico_title: "Maçarico",
            item_macarico_desc: "Ginebra de jambu, limón siciliano, jarabe de azúcar y angostura.",

            item_olho_grego_title: "Olho Grego",
            item_olho_grego_desc: "Ginebra, Blue Curacao, limón siciliano y espuma de jengibre.",
            item_la_passion_title: "La Passion",
            item_la_passion_desc: "Vodka, fresa, pitaya roja, azúcar y hielo.",

            section_drinks_subtitle_atuais: "Clásicos Modernos",
            item_moscow_mule_title: "Moscow Mule",
            item_moscow_mule_desc: "Vodka, limón siciliano, jarabe de jengibre y espuma de jengibre.",
            item_gin_mule_title: "Gin Mule",
            item_gin_mule_desc: "Ginebra, limón siciliano, jarabe de jengibre y espuma de jengibre.",
            item_gin_tonica_title: "Gin Tónico",
            item_gin_tonica_desc: "Ginebra, agua tónica y especias.",
            item_spritz_aperol_title: "Aperol Spritz",
            item_spritz_aperol_desc: "Vino espumoso, Aperol y agua con gas.",
            item_mimosa_title: "Mimosa",
            item_mimosa_desc: "Vino espumoso y jugo de naranja.",

            section_drinks_subtitle_antologicos: "Cócteles Clásicos",
            item_negroni_title: "Negroni",
            item_negroni_desc: "Ginebra, vermut, Campari y twist de naranja.",
            item_mojito_title: "Mojito",
            item_mojito_desc: "Ron, limón y menta.",
            item_marguerita_title: "Margarita",
            item_marguerita_desc: "Tequila, Cointreau, Blue Curacao y limón.",
            item_maracujack_desc: "Jack Daniel's, maracuyá y azúcar.",
            item_caipirosca_title: "Caipirosca",
            item_caipirosca_desc: "Vodka importada, frutas de temporada, azúcar y hielo.",
            item_caipirinha_title: "Caipirinha",
            item_caipirinha_desc: "Cachaça, limón, azúcar y hielo.",
            item_coquetel_frutas_title: "Cóctel de Frutas",
            item_coquetel_frutas_desc: "Mezcla de frutas, vodka, leche condensada, crema, jarabe de grosella y crema batida.",

            section_drinks_subtitle_sem_alcool: "Sin Alcohol",
            item_coquetel_frutas_sem_alcool_title: "Cóctel de Frutas",
            item_coquetel_frutas_sem_alcool_desc: "Mezcla de frutas, leche condensada, crema, jarabe de grosella y crema batida.",

            section_saladas_title: "Ensaladas",
            item_salada_caesar_title: "Ensalada César",
            item_salada_caesar_desc: "Mezcla de hojas, tiras de pollo a la parrilla, picatostes y parmesano con aderezo César.",
            item_salada_feijao_manteiguinha_title: "Ensalada de Frijoles",
            item_salada_feijao_manteiguinha_desc: "Mezcla de hojas, vinagreta de frijoles 'manteiguinha', tomate, zanahoria, calabacín y queso.",

            section_mariscos_title: "Pescado y Camarones",
            item_pescada_tucupi_title: "Merluza a la Parrilla con Crema de Tucupi",
            item_pescada_tucupi_desc: "Arroz con tucupi y jambu, y salsa de camarones",
            item_pescada_camarao_title: "Merluza a la Parrilla con Salsa de Camarones",
            item_pescada_camarao_desc: "Arroz blanco y puré de papas",
            item_camarao_solar_title: "Camarones Crujientes Solar",
            item_camarao_solar_desc: "Empanizados y gratinados con queso, servidos con arroz Piamontese y papas fritas",
            item_caldeirada_pescada_title: "Guiso de Merluza Amarilla",
            item_caldeirada_pescada_desc: "Merluza, camarones, huevo duro, verduras, arroz blanco y salsa",
            item_peixe_frito_regional_title: "Pescado Frito Regional",
            item_peixe_frito_regional_desc: "Arroz blanco, harina de yuca y vinagreta de frijoles",
            item_pescada_solar_title: "Merluza Solar",
            item_pescada_solar_desc: "Empanizada en harina especial, arroz cremoso y puré de papas.",

            section_peixes_title: "Risotto y Pasta",
            item_peixe_amazonico_title: "Pescado Amazónico en Costra de Ajo",
            item_peixe_amazonico_desc: "Pescado Filhote, risotto de parmesano y salsa de aceitunas negras",
            item_espaguete_bolonhesa_title: "Espagueti a la Boloñesa",
            item_espaguete_bolonhesa_desc: "Porción individual",

            section_carnes_title: "Carnes",
            item_file_alfredo_title: "Filete Alfredo",
            item_file_alfredo_desc: "Filete a la parrilla y fettuccine con crema de parmesano y aroma de tocino",
            item_file_solar_title: "Filete Solar",
            item_file_solar_desc: "A la parrilla con salsa de cebolla, arroz Piamontese, papas fritas y farofa de huevo",
            item_file_grelhado_solar_title: "Filete a la Parrilla Solar",
            item_file_grelhado_solar_desc: "A la parrilla, arroz, farofa y papas fritas",

            section_kids_title: "Niños",
            item_file_cubinhos_title: "Cubos de Filete",
            item_file_cubinhos_desc: "Cubos a la parrilla, arroz blanco, farofa de huevo y papas fritas",
            item_isca_milanesa_title: "Tiras de Pescado Empanizadas",
            item_isca_milanesa_desc: "Merluza, arroz blanco, farofa y puré de papas",

            section_caldos_title: "Sopas y Caldos",
            section_caldos_subtitle: "(porción individual, servida con tostadas)",
            item_sopa_caranguejo_title: "Sopa de Cangrejo",
            item_canja_title: "Sopa de Pollo",
            item_caldo_legumes_title: "Caldo de Verduras",
            item_caldo_tucupi_title: "Caldo de Tucupi",
            item_caldo_tucupi_desc: "Jambu y camarones",

            section_burgers_title: "Hamburguesas",
            section_burgers_subtitle: "Servido con ensalada de hojas mixtas, tomate, zanahoria rallada y cebolla roja",
            item_file_do_reino_title: "Filete del Reino",
            item_file_do_reino_desc: "Pan baguette, filete, queso del reino y papas fritas",
            item_burger_solar_title: "Hamburguesa Solar",
            item_burger_solar_desc: "Pan, mezcla artesanal, queso, pepperoni, huevo y papas rústicas",
            item_burger_kids_title: "Hamburguesa para Niños",
            item_burger_kids_desc: "Pan, mezcla artesanal y queso",

            section_porcoes_title: "Porciones",
            item_feijao_title: "Frijoles",
            item_pure_title: "Puré de Papas",
            item_arroz_branco_title: "Arroz Blanco",
            item_arroz_piamontese_title: "Arroz Piamontese",
            item_farofa_simples_title: "Farofa Simple",
            item_farofa_banana_title: "Farofa de Plátano",
            item_farofa_ovo_title: "Farofa de Huevo",
            item_vinagrete_title: "Vinagreta",
            item_torrada_title: "Tostadas",

            section_sobremesas_title: "Postres",
            item_salada_frutas_solar_title: "Ensalada de Frutas Solar",
            item_salada_frutas_solar_desc: "Frutas de temporada, yogur natural y mermelada de fresa",
            item_pudim_leite_title: "Flan de Leche",
            item_sufle_chocolate_title: "Soufflé de Chocolate",
            item_sufle_chocolate_desc: "Pastel caliente, ganache de chocolate y fresas picadas",
            item_brulee_cupuacu_title: "Brulée de Cupuaçu",
            item_brulee_cupuacu_desc: "Crema de Cupuaçu con cobertura brulée",
            item_duo_brownie_title: "Duo Brownie",
            item_duo_brownie_desc: "Brownie, helado de vainilla, crema de chocolate",
            item_tartelete_morango_title: "Tartaleta de Fresa",
            item_tartelete_morango_desc: "Masa crujiente, crema pastelera, fresa y crema batida",

            section_bebidas_title: "Bebidas",
            section_bebidas_subtitle_cervejas: "Cervezas",
            item_cervejas_list_title: "Tijuca Pilsen, Tijuca Puro Malte, Kroland y Silver",
            item_cerpa_export_title: "Cerpa Export",
            section_bebidas_subtitle_doses: "Tragos",
            item_whisky_old_parr_title: "Likoz Old Parr",
            item_whisky_red_title: "Johnnie Walker Red Label",
            item_vodka_importada_title: "Vodka (Importada)",
            item_tequila_title: "Tequila",
            item_cointreau_title: "Cointreau",
            item_rum_title: "Ron",
            item_gin_title: "Ginebra",
            item_cachaca_jambu_title: "Cachaça de Jambu",
            section_bebidas_subtitle_nao_alcoolicos: "Sin Alcohol",
            item_agua_sem_gas_title: "Agua Natural",
            item_agua_com_gas_title: "Agua Con Gas",
            item_refrigerante_lata_title: "Refresco (Lata)",
            item_sucos_title: "Jugos (Consultar al mesero)",
            item_shot_verde_solar_title: "Jugo Verde Solar",
            item_shot_limao_title: "Shot de Limón",
            item_agua_tonica_title: "Agua Tónica Schweppes",
            item_agua_coco_title: "Agua de Coco (Consultar al mesero)",
            item_energetico_title: "Bebida Energética Red Bull",
            item_milkshake_title: "Batido",
            item_milkshake_desc: "Chocolate, fresa y açaí",
            item_vitamina_title: "Batido Vitamínico",
            item_vitamina_desc: "Papaya, plátano y leche",
            item_cafe_expresso_title: "Café Expreso",

            footer_prohibit_smoking: "No Fumar",
            footer_prohibit_coolers: "No Hieleras",
            footer_prohibit_pets: "No Mascotas",
            footer_prohibit_sound: "No Altavoces",
            nav_cerpa: "Cervezas Cerpa",
            section_cerpa_title: "Espacio Cerpa",
            section_cerpa_subtitle: "Cervezas Premium de Nuestro Patrocinador Oficial",
            cerpa_badge_premium: "Premium",
            cerpa_badge_puro: "Puro Malte",
            cerpa_badge_refrescante: "Refrescante",
            cerpa_badge_gold: "Gold",
            cerpa_label_pairing: "Armoniza con:",
            cerpa_label_temp: "Temperatura:",
            item_cerpa_export_title_sec: "Cerpa Export",
            item_cerpa_export_desc_sec: "La cerveza premium más tradicional de la Amazonia. Elaborada con lúpulos especiales y agua de altísima pureza, posee cuerpo medio y sabor refinado.",
            item_cerpa_export_pairing: "Pescados a la parrilla, mariscos, salmón ahumado y quesos suaves.",
            item_tijuca_pilsen_title: "Tijuca Pilsen",
            item_tijuca_pilsen_desc: "Una cerveza ligera y de alta calidad. Ideal para días calurosos en la playa, aportando una suavidade perfecta y frescura extrema.",
            item_tijuca_pilsen_pairing: "Iscas de pescado crujiente, papas fritas, croquetas y aperitivos de playa.",
            item_tijuca_puromalte_title: "Tijuca Puro Malte",
            item_tijuca_puromalte_desc: "El equilibrio perfecto entre frescura y personalidad. Cerveza puro malte con más corpo, manteniendo la frescura de Río.",
            item_tijuca_puromalte_pairing: "Hamburguesas artesanales, carnes a la brasa y quesos de mediana curación.",
            item_cerpa_kroland_title: "Cerpa Kroland",
            item_cerpa_kroland_desc: "Una auténtica cerveza puro malta de inspiración alemana. Ligera y refrescante, con un sabor equilibrado que une la tradición europea a la pureza amazónica.",
            item_cerpa_kroland_pairing: "Pasteles aperitivos, mandioca frita, papas fritas y buñuelos de bacalao.",
            item_cerpa_gold_title_sec: "Cerpa Gold",
            item_cerpa_gold_desc: "Una cerveza clásica, ligera y extremadamente sabrosa, ideal para momentos de relax y para combatir el calor.",
            item_cerpa_gold_pairing: "Porciones variadas de aperitivos, papas fritas y enasladas frescas.",
            cerpa_badge_gluten_free: "Sin Gluten",
            item_tijuca_silver_title: "Tijuca Silver",
            item_tijuca_silver_desc: "Cerveza premium sin gluten, ligera y refrescante. La opción ideal para quienes buscan equilibrio y sabor sin restricciones.",
            item_tijuca_silver_pairing: "Pescados a la parrilla, ensaladas ligeras, aperitivos y platos suaves."
        }
    };

    function updateContent(lang) {
        if (!translations[lang] && lang !== 'pt') {
            console.warn(`Translation not found for language: ${lang}. Falling back to PT.`);
            // You might want to implement a deep fallback, but for now we assume EN is done or default to PT keys
            if (lang === 'fr' || lang === 'it' || lang === 'es') {
                // For now, if other languages are missing, fallback to English or keep original text
                // A better approach for this MVP is to reuse English for missing languages or just let it be.
                // Ideally, we would have full dictionaries.
                // For this task, I provided full PT and EN. I will create simple fallbacks for others for demo.
            }
        }

        let dict = translations[lang] || translations['pt'];

        // Fallback for missing keys in target language to PT
        const ptDict = translations['pt'];

        translatableElements.forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (key) {
                const translation = dict[key] || ptDict[key]; // Fallback to PT if key missing
                if (translation) {
                    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                        el.placeholder = translation;
                    } else {
                        el.textContent = translation;
                    }
                }
            }
        });

        // Update active button
        langButtons.forEach(btn => {
            if (btn.getAttribute('data-lang') === lang) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });

        localStorage.setItem('language', lang);
    }

    langButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            const lang = btn.getAttribute('data-lang');
            updateContent(lang);
        });
    });

    // Initialize
    updateContent(currentLang);
});
